In [2]:
#1
import numpy as np
a = np.arange(26)
a = a.reshape(2,-1)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]


In [3]:
#2
b = a.T
# print(b)
# print(a)
c = a.reshape(13,2)
# print(c)
# Transpose를 사용한것은 축(Axis) 자체가 바뀌지만
# reshape는 모양만 바꿔서 보여주는 것입니다
# 즉 숫자가 채워지는 순서가 다릅니다


In [4]:
#3
a = np.arange(27).reshape(3,3,3)
for i in range(3):
    a[i,1,1] = 999
print(a)

[[[  0   1   2]
  [  3 999   5]
  [  6   7   8]]

 [[  9  10  11]
  [ 12 999  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21 999  23]
  [ 24  25  26]]]


In [5]:
#4
a = np.zeros((4,4), dtype = np.float32)
print(a + 10)
a = np.ones((4,4), dtype = np.float32)
print(a + 9)
a = np.full((4,4), 10, dtype=np.float32)
print(a)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [6]:
#5
a = np.full((5,4), -999, dtype=np.float32)
b = np.arange(20).reshape(5,4)

c = np.vstack((b,a))
print(c)



[[   0.    1.    2.    3.]
 [   4.    5.    6.    7.]
 [   8.    9.   10.   11.]
 [  12.   13.   14.   15.]
 [  16.   17.   18.   19.]
 [-999. -999. -999. -999.]
 [-999. -999. -999. -999.]
 [-999. -999. -999. -999.]
 [-999. -999. -999. -999.]
 [-999. -999. -999. -999.]]


In [7]:
#6
a = np.full((5,4), -999, dtype=np.float32)
b = np.arange(20).reshape(5,4)
c = np.hstack((b,a))
print(c)

[[   0.    1.    2.    3. -999. -999. -999. -999.]
 [   4.    5.    6.    7. -999. -999. -999. -999.]
 [   8.    9.   10.   11. -999. -999. -999. -999.]
 [  12.   13.   14.   15. -999. -999. -999. -999.]
 [  16.   17.   18.   19. -999. -999. -999. -999.]]


In [8]:
#7
#np.exp로 할때는 data에 있는 모든 요소에 exp가 적용될거 같고
#math 모듈에서 가져온 exp는 반복문으로 각각의 요소에 적용시켜 주어야 할거 같습니다
#그냥 exp(data)로 코드를 실행한다면 실행이 되지않고 type이 맞지 않아 오류가 날거 같습니다

In [9]:
#8
a = np.random.rand(4,)
b = np.random.randn(4,3)
c = np.ones((1,4), dtype = np.float32)
print(a)
print(b)
print(c + 4)

[0.03041192 0.87614985 0.83132031 0.26595024]
[[-0.45250174  0.37375855  0.64749106]
 [ 1.06658909 -0.16197045  1.35724921]
 [ 1.36807573 -1.59656347  0.88688772]
 [-0.55616805  1.23660059  0.8112468 ]]
[[5. 5. 5. 5.]]


In [10]:
#9
print(a.shape)
print(c.shape)
# a.T는 (4,) 형태입니다 b와 연산이 가능하려면 (3,) 형태여야합니다
# c.T는 (4,1) 형태 이므로 b와 행의 개수가 일치하여 c.T가 b와 사칙연산이 가능할 거 같습니다

(4,)
(1, 4)


In [11]:
#10
print(f'b + a = {b.T + a}')
print(f'b + c = {b+c.T}')

b + a = [[-0.42208982  1.94273893  2.19939603 -0.29021781]
 [ 0.40417047  0.7141794  -0.76524316  1.50255083]
 [ 0.67790298  2.23339906  1.71820802  1.07719704]]
b + c = [[ 0.54749826  1.37375855  1.64749106]
 [ 2.06658909  0.83802955  2.35724921]
 [ 2.36807573 -0.59656347  1.88688772]
 [ 0.44383195  2.23660059  1.8112468 ]]


In [12]:
#11
a = np.linspace(0,1,11)
b = np.arange(0,1.1,0.1)
print(f'Using linspace : {a}')
print(f'Using arange : {b}')

Using linspace : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
Using arange : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
#12
a = np.ones((5,5),dtype = np.float32)
b = [-2,-1,0,1,2]
matrix = a*b
print(matrix)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


In [14]:
#13
np.random.seed(10)
a = np.random.randint(-5,6,size=(5,5))
matrix = matrix - a
print(matrix)


[[-6.  0.  5.  5. -2.]
 [ 3.  3. -5. -2. -2.]
 [ 3. -6. -3.  0.  3.]
 [ 0.  4.  1.  0. -1.]
 [-7.  3. -3.  2.  6.]]


In [15]:
#14
matrix[matrix<0] = 0
print(matrix)

[[0. 0. 5. 5. 0.]
 [3. 3. 0. 0. 0.]
 [3. 0. 0. 0. 3.]
 [0. 4. 1. 0. 0.]
 [0. 3. 0. 2. 6.]]


In [16]:
#15
p = np.arange(1,6).reshape((1,5))
print(np.tile(p,(2,2)))

[[1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]]


In [17]:
#16
p = np.arange(1,7).reshape((1,2,-1))
print(np.repeat(p,2,axis = 0))
print()
print(np.repeat(p,3,axis = 1))
print()
print(np.repeat(p,4,axis = 2))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]
  [4 5 6]]]

[[[1 1 1 1 2 2 2 2 3 3 3 3]
  [4 4 4 4 5 5 5 5 6 6 6 6]]]


In [18]:
#17
a = np.array([84, 91, 13, 65, 8,31 ,48,4])
print(f'max value index : {np.argmax(a)}')
print(f'min value index : {np.argmin(a)}')

max value index : 1
min value index : 7


In [19]:
#18
a = np.random.uniform(-100,101,size = 10000000)
print(f'min value : {a.min()}')
print(f'max value : {a.max()}')
print(f'mean value : {a.mean()}')
print(f'standard deviation value : {a.std()}')

min value : -99.99996883988948
max value : 100.99998989161892
mean value : 0.5248372062148629
standard deviation value : 58.03300936826417


In [20]:
#19
a = np.random.normal(5,2,size=10000000)
print(f'min value : {a.min()}')
print(f'max value : {a.max()}')
print(f'mean value : {a.mean()}')
print(f'standard deviation value : {a.std()}')

min value : -5.203910465271903
max value : 15.079142663647524
mean value : 5.000486114200695
standard deviation value : 1.9998314293370025


In [21]:
#20
a = [[4,1],
     [2,4]]
b = [[5,6],
     [1,8]]
a = np.array(a)
b = np.array(b)
print((a@b)@(b@a))

[[1312 1665]
 [1328 1858]]


In [22]:
#21
c = [[1,2],
     [8,4],
     [3,9]]
c = np.array(c)
#(a@c)+(b@c) 가 계산이 안되는 이유는 a,b의 열의 수와 c의 행의 개수가 맞지 않기 때문입니다
print((c@a) + (c@b))

[[ 15  31]
 [ 84 104]
 [ 54 129]]


In [23]:
#22
k = np.ones((3,4)) * np.linspace(-1,2.5,4)
print(f"높임 : {np.ceil(k)}")
print(f"내림 : {np.floor(k)}")
print(f"반올림 : {np.round(k)}")


높임 : [[-1.  1.  2.  3.]
 [-1.  1.  2.  3.]
 [-1.  1.  2.  3.]]
내림 : [[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]
반올림 : [[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]


In [24]:
#23
#cumsum은 누적합을 구해주는 함수인거 같습니다

In [25]:
#24
random_value = np.array([13,20,28,38,14,41,0,37])
random_value = random_value[:,np.newaxis]
print(random_value)

[[13]
 [20]
 [28]
 [38]
 [14]
 [41]
 [ 0]
 [37]]


In [26]:
#25

print(np.sort(random_value,axis=0))
print(random_value[random_value[:,0].argsort()])

[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
