## Classification

In [275]:
# K-Nearest Neighbors (Regression에서도 쓸 수 있음)
# K는 정확도가 제일 높은 값으로 한다 (Hyperparameter -> 사람이 정해줘야함)

In [276]:
from sklearn import datasets

iris = datasets.load_iris()

In [277]:
import numpy as np
X, Y = iris.data, iris.target
print(X.shape,Y.shape)
print(X[:10])
print(iris.feature_names, iris.target_names)
print(Y)

(150, 4) (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [278]:
# preprocessing
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_std = sc_X.fit_transform(X)

print(sc_X.mean_)
print(sc_X.scale_)

print(X_std[:10])

# Note: target class does not need to be standardized

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]


In [279]:
from sklearn.model_selection import train_test_split

X_train, X_test,Y_train, Y_test = train_test_split(X_std,Y,test_size=0.3)

print(X_train.shape,X_test.shape)
print(Y_train.shape,Y_test.shape)

(105, 4) (45, 4)
(105,) (45,)


In [280]:
#model setting

from sklearn import neighbors
from my_knn import MyKNN
# model = neighbors.KNeighborsClassifier(n_neighbors=5)
model = MyKNN(n_neighbors=5)

In [281]:
#model fitting
model.fit(X_train,Y_train)

In [282]:
# test
Y_pred = model.predict(X_test)
print(Y_test)
print(Y_pred)

[2 1 1 0 1 2 1 2 1 1 2 1 1 2 0 1 2 1 1 2 0 1 2 1 0 1 0 0 0 0 2 2 1 0 2 0 1
 2 1 2 2 1 0 0 0]
[1 2 2 2 1 2 0 1 1 1 0 1 0 1 2 2 0 1 2 1 1 2 2 1 1 2 0 0 1 0 2 1 0 1 1 0 2
 0 2 2 1 1 1 2 1]


In [283]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

print(f"confusion matrix: \n {confusion_matrix(Y_test,Y_pred)}")
print(f"accuracy: {accuracy_score(Y_test, Y_pred):.3f}")
print(f"precesion: {precision_score(Y_test,Y_pred,average=None)}")
print(f"recall: {recall_score(Y_test,Y_pred,average=None)}")
print(f"f1: {f1_score(Y_test,Y_pred,average=None)}")

confusion matrix: 
 [[4 6 3]
 [3 7 8]
 [3 7 4]]
accuracy: 0.333
precesion: [0.4        0.35       0.26666667]
recall: [0.30769231 0.38888889 0.28571429]
f1: [0.34782609 0.36842105 0.27586207]
