## Numpy

In [2]:
import numpy as np

In [3]:
#scalars, vectors, martices, and tensors
#a = np.array(15)
#a = np.array([2,3,7,10,-1,2])
#a = np.array([[2,3,4],[5,6,7]])
a = np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7]]]) #rank 3 tensor
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape) #tuple 형태로 나옴

[[[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]]
<class 'numpy.ndarray'>
3
int64
(2, 2, 3)


In [4]:
# list vs ndarray
import time

a = list(range(100000))
b = list(range(100000,200000))
start = time.time()
for _ in range(1000):
    c = [i + j for i, j in zip(a, b)]
end = time.time()
print(c[:10])
print(f'{end - start:.6f}')

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
2.730363


In [5]:
na = np.array(a)
nb = np.array(b)
start = time.time()
for _ in range(1000):
    nc = na + nb
end = time.time()

print(nc[:10])
print(f'{end - start:.6f}')

[100000 100002 100004 100006 100008 100010 100012 100014 100016 100018]
0.041053


## vector

In [6]:
#a = np.zeros((2,5), dtype = np.float32)
#a = np.ones((2,5))
# a = np.empty((2,5))
# a = np.full((2,5),7,dtype=np.float32)
# print(a)
# print(a.dtype)
# print(a.shape) 
#help(np.arange)

In [7]:
a = np.arange(0,10,0.1, dtype = np.float32) # step이 있고 끝에 값이 보통 포함이 안된다
print(a)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004 1.         1.1
 1.2        1.3000001  1.4        1.5        1.6        1.7
 1.8000001  1.9        2.         2.1000001  2.2        2.3
 2.4        2.5        2.6000001  2.7        2.8        2.9
 3.         3.1000001  3.2        3.3        3.4        3.5
 3.6000001  3.7        3.8        3.9        4.         4.1
 4.2000003  4.3        4.4        4.5        4.6        4.7000003
 4.8        4.9        5.         5.1        5.2000003  5.3
 5.4        5.5        5.6        5.7000003  5.8        5.9
 6.         6.1        6.2000003  6.3        6.4        6.5
 6.6        6.7000003  6.8        6.9        7.         7.1
 7.2000003  7.3        7.4        7.5        7.6        7.7000003
 7.8        7.9        8.         8.1        8.2        8.3
 8.400001   8.5        8.6        8.7        8.8        8.900001
 9.         9.1        9.2        9.3        9.400001   9.5
 9.6        9.7        

In [8]:
# help(np.linspace)
# help(np.arange)
a = np.linspace(0,10,20) # 값의 개수에 중점을 둔다
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [ ]:
#random
np.random.seed(1)
# help(np.random.randint)
# a = np.random.randint(0,10,size=(2,3),dtype=np.int32) #균등분포 (모두 동일한 확률로 뽑음)
# help(np.random.uniform)
# a= np.random.uniform(0,10,size=(2,3)) #균등분포
# a = np.random.rand(10) #[0,1) 구간 실수 반환 균등분포
# help(np.random.normal)
# a = np.random.normal(10,0.001,size=(10,)) # 평균과 표준편차 직접 지정
# a = np.random.randn(2,3) # 평균이 0이고 표준편차가 1인 가우시안 정규분포 
print(a)


[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [10]:
a = np.random.rand(6)
a = a.reshape(2,3)
print(a)
print()
print(a.T)
print(a.T.shape)

[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]]

[[0.18626021 0.53881673]
 [0.34556073 0.41919451]
 [0.39676747 0.6852195 ]]
(3, 2)


In [11]:
#indexing
a = np.arange(20)
print(a)
# print(a[3])
print(a[:3])
print(a[1:7])
# b = a[:5] #copy가 아님, 원본 데이터 같이 수정됨
b = a[:5].copy() # 별도의 copy 필요
b[0] = 100
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2]
[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
# fancy indexing
a = np.random.randint(0,10,size=(10,))
print(a)
b = a[[i for i in range(len(a)) if i%2==0]] # fancy indexing은 copy, index로 리스트를 넘겨버려
# b[0] = 100
print(b)

[2 4 7 7 9 1 7 0 6 9]
[2 7 9 7 6]


In [ ]:
# boolean indexing, copy임
a = np.random.uniform(-1, 1, size=(10,))
print(a)

b = a< 0
print(b)

print(a[a<0])# 츄르인 녀석만 뽑아버려

a[a<0] = 0
print(a)

[ 0.93652315 -0.37315164  0.38464523  0.7527783   0.78921333 -0.82991158
 -0.92189043 -0.66033916  0.75628501 -0.80330633]
[False  True False False False  True  True  True False  True]
[-0.37315164 -0.82991158 -0.92189043 -0.66033916 -0.80330633]
[0.93652315 0.         0.38464523 0.7527783  0.78921333 0.
 0.         0.         0.75628501 0.        ]


In [75]:
a = np.random.randint(1,10,size=(2,5))
print(a)
print(a%2==0)
print(a[a%2==0])
a[a%2==0] = 0
print(a)

[[6 3 5 3 5]
 [8 8 2 8 1]]
[[ True False False False False]
 [ True  True  True  True False]]
[6 8 8 2 8]
[[0 3 5 3 5]
 [0 0 0 0 1]]


In [81]:
# operations
a = np.random.randint(1,10,(5,5))
b = np.random.randint(1,10,(5,1))
print(a)
print(b)
print(a + b)
print(a * b)#element-wise multiplication, 원소별 곱
print(a / b)
print(a // b)
print(a % b)
print(a ** 2)
print(a ** b)

[[3 9 3 2 5]
 [1 5 2 8 4]
 [2 7 7 7 7]
 [1 1 3 7 1]
 [7 8 1 4 1]]
[[4]
 [5]
 [8]
 [6]
 [4]]
[[ 7 13  7  6  9]
 [ 6 10  7 13  9]
 [10 15 15 15 15]
 [ 7  7  9 13  7]
 [11 12  5  8  5]]
[[12 36 12  8 20]
 [ 5 25 10 40 20]
 [16 56 56 56 56]
 [ 6  6 18 42  6]
 [28 32  4 16  4]]
[[0.75       2.25       0.75       0.5        1.25      ]
 [0.2        1.         0.4        1.6        0.8       ]
 [0.25       0.875      0.875      0.875      0.875     ]
 [0.16666667 0.16666667 0.5        1.16666667 0.16666667]
 [1.75       2.         0.25       1.         0.25      ]]
[[0 2 0 0 1]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [1 2 0 1 0]]
[[3 1 3 2 1]
 [1 0 2 3 4]
 [2 7 7 7 7]
 [1 1 3 1 1]
 [3 0 1 0 1]]
[[ 9 81  9  4 25]
 [ 1 25  4 64 16]
 [ 4 49 49 49 49]
 [ 1  1  9 49  1]
 [49 64  1 16  1]]
[[     81    6561      81      16     625]
 [      1    3125      32   32768    1024]
 [    256 5764801 5764801 5764801 5764801]
 [      1       1     729  117649       1]
 [   2401    4096       1     256       

In [16]:
# operations: broadcasting
a = np.arange(10)
print(a)
b = a + 10
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [82]:
# operations
a = np.arange(1,11)
print(a)
print(np.sin(a))
print(np.cos(a))
print(np.log2(a))#자연로그
print(np.log10(a))

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


In [18]:
# operations
a = np.random.randint(0,100,size=(10,))
print(a)
# print(np.max(a))
# print(np.min(a))
# print(np.mean(a))
# print(np.argmax(a))
# print(np.argmin(a))
print(a.max())
print(a.min())
print(a.mean())
print(a.argmax())
print(a.argmin())

[23 27 37 57 83 38  8 32 34 10]
83
8
34.9
4
6


In [19]:
# dot product, 내적
a = np.array([1,2,3])
b = np.array([3,0,1])

print(a * b)
print(np.dot(a,b))
print(a.dot(b))
print(a @ b)

[3 0 3]
6
6
6


In [20]:
# compare np.dot vs list
a = list(range(100000))
b = list(range(100000))

na = np.array(a)
nb = np.array(b)


In [21]:
%%timeit
np.dot(na,nb)



38.2 μs ± 1.29 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [22]:
%%timeit
r1 = sum([i*j for (i,j) in zip(a,b)])

3.99 ms ± 160 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
def softmax(z):
    z= np.exp(z)
    a =np.sum(z)
    return z/a


logits = np.array([2.0,1.0,-1.0])
probs = softmax(logits)
print(probs)

[0.70538451 0.25949646 0.03511903]


## 2D, 3D arrayes

In [24]:
a = np.random.randint(0,20,size=(3,4,5))
print(a)
print(a.shape)
print(a.ndim)
print(a.mean(axis=(0,2),keepdims=True))

[[[15 15  7 19 10]
  [14  0  1 17 13]
  [ 3  0 13  6  6]
  [ 2 12 11  7 13]]

 [[ 8 11 12 11  4]
  [ 7  7 13  4 16]
  [18  0 13 10 17]
  [ 7 10  0 12  1]]

 [[ 9 18 19  1  2]
  [12  7  2 10  0]
  [ 9 18  6  2  7]
  [ 7 16 15  5 17]]]
(3, 4, 5)
3
[[[10.73333333]
  [ 8.2       ]
  [ 8.53333333]
  [ 9.        ]]]


In [25]:
# indexing 
a = np.random.randint(0,20,size=(4,5))
print(a)
print(a[2,3])
#b = a[:3,:3]
b = a[::2,::2] # slicing : make a view
print(b)
b[0,0] = 100
print(a)
c = a[:,[0,1]] #fancy indexing : make a copy
print(c)
c[0,0] = 1000
print(a)

[[10 16  5 13 17]
 [18  1 10  0  7]
 [ 0 19 17 14 13]
 [11  6 13 15  9]]
14
[[10  5 17]
 [ 0 17 13]]
[[100  16   5  13  17]
 [ 18   1  10   0   7]
 [  0  19  17  14  13]
 [ 11   6  13  15   9]]
[[100  16]
 [ 18   1]
 [  0  19]
 [ 11   6]]
[[100  16   5  13  17]
 [ 18   1  10   0   7]
 [  0  19  17  14  13]
 [ 11   6  13  15   9]]


In [87]:
#reshaping
a =np.arange(20)
print(a)
print(a.shape)
b = a.reshape((-1,5))
print(b.reshape(2,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [27]:
a = np.arange(10)
a = a.reshape(2,5)
print(a)
print(a[0])
print(a.shape)
# b = a[:,None]
# b = a[None,:]
b = a[np.newaxis,:,:]
print(b)
# print(b.shape)
# # c = b.reshape((10,))
# # c=b.reshape(-1) # return a view
# c = b.flatten() # return a copy
# print(c)
# print(c.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
(2, 5)
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [ ]:
# transpose
a = np.arange(10).reshape((5,-1))
print(a)
b = a.T
b[0][0] = 100
print(a.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[100   2   4   6   8]
 [  1   3   5   7   9]]


In [29]:
#broadcasting
a = np.arange(12).reshape((3,-1))
print(a.shape)
# print(a*10)
# b = np.array([1,1,1,1])
b = np.array([1,0,-1])
print(b.shape)
b = b[:,None]
print(b + a)


(3, 4)
(3,)
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [108]:
#sum(), mean(), min(), max(), argmin(), argmax()
np.random.seed(1)
a = np.random.randint(0,24,size=(2,3,4))
print(a)
b = a.sum(axis=(0,2))
# a.min()
# a.max()
print(a.mean(axis=(0,2)))
print(b)
print(b.shape)

[[[ 5 11 12  8]
  [ 9 11  5 15]
  [ 0 16  1 12]]

 [[ 7 13  6 18]
  [20  5 18 20]
  [11 10 14 18]]]
[10.    12.875 10.25 ]
[ 80 103  82]
(3,)


In [71]:
# sorting
a = np.random.randint(1,20,size=(4,5))
print(a)
# a.sort(axis=0) in-place sorting
# print(a)
b = np.sort(a,axis=1) # return a sorted copy
c = np.argsort(a,axis = 1)
print(b)
print(c)
# print(a[c,np.array([i for i in range(c.shape[1])])])
print(a[np.arange(c.shape[0])[:, np.newaxis], c])
print(a[np.arange(c.shape[0])[:, np.newaxis]])
# print(a)

[[18  9  7  5  7]
 [13 10  6 16  8]
 [12  3  1 15 12]
 [19 13  1  6 16]]
[[ 5  7  7  9 18]
 [ 6  8 10 13 16]
 [ 1  3 12 12 15]
 [ 1  6 13 16 19]]
[[3 2 4 1 0]
 [2 4 1 0 3]
 [2 1 0 4 3]
 [2 3 1 4 0]]
[[ 5  7  7  9 18]
 [ 6  8 10 13 16]
 [ 1  3 12 12 15]
 [ 1  6 13 16 19]]
[[[18  9  7  5  7]]

 [[13 10  6 16  8]]

 [[12  3  1 15 12]]

 [[19 13  1  6 16]]]


In [32]:
a = np.random.randint(1,20, size=(10))
print(a)
c = np.argsort(a)
print(c)
print(a[c])

[ 7 18  4  5 18 12 13 17 14 10]
[2 3 0 9 5 6 8 7 4 1]
[ 4  5  7 10 12 13 14 17 18 18]


In [33]:
a = np.array([1,2,3])
a = a[np.newaxis,:,np.newaxis]
print(a)
print(a.shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)
